#!/usr/bin/env node

const net = require('net')
const { render, handle_input, handle_message, send_message, red } = require('./lib/helpers')
const conn = net.createConnection('./bank.sock')



function connection_ready() {
	render([
		'Hello Customer'
	])
}



function connection_closed() {
	console.log('connection closed')
}



handle_input(line => {
	console.log(`Prompt command entered:`, line)
	send_message(conn, line)
})



handle_message(conn, message => {
	console.log('Message received:', message)
})










conn.on('ready', connection_ready)

conn.on('close', (has_error) => {
  if (has_error) {
    return
  }
	connection_closed()
	process.exit(1)
})

conn.on('error', () => {
	render([
		`The Bank is ${red('closed')}.`
	])
})